version: '3.6'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
      PLICA_network:
        ipv4_address: 192.168.3.10


  kafka:
    image: wurstmeister/kafka:0.11.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: "42"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
    networks:
      PLICA_network:
        ipv4_address: 192.168.3.11


  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
  #   container_name: elasticsearch01
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"      
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - cluster.routing.allocation.disk.threshold_enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   networks:
  #     PLICA_network:
  #       ipv4_address: 192.168.1.12


  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.5.2
  #   container_name: kibana
  #   ports:
  #     - 5601:5601
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch01:9200
  #     ELASTICSEARCH_HOSTS: http://elasticsearch01:9200
  #   networks:
  #     PLICA_network:
  #       ipv4_address: 192.168.1.13


  # connect:
  #   image: confluentinc/cp-kafka-connect:3.3.0
  #   ports:
  #     - 8083:8083
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   volumes:
  #     - $PWD/connect-plugins:/connect-plugins
  #   environment:
  #     CONNECT_BOOTSTRAP_SERVERS: kafka:9092
  #     CONNECT_REST_PORT: 8083
  #     CONNECT_GROUP_ID: "connect"
  #     CONNECT_CONFIG_STORAGE_TOPIC: connect-config
  #     CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
  #     CONNECT_STATUS_STORAGE_TOPIC: connect-status
  #     CONNECT_REPLICATION_FACTOR: 1
  #     CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
  #     CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
  #     CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
  #     CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
  #     CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  #     CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
  #     CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  #     CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  #     CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
  #     CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
  #     CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
  #     CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
  #     CONNECT_PLUGIN_PATH: /connect-plugins
  #     CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
  #     CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
  #     CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-3.3.0.jar
  #   networks:
  #     PLICA_network:
  #       ipv4_address: 192.168.1.14



networks:
   PLICA_network:
      name: PLICA
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: "192.168.3.0/24"
